// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    facilities_by_capacity: {
        name: "facilities_by_capacity";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          band: string;
          /** @sqlType BIGINT */
          facilities: number;
        }>;
      };
    facilities_by_city: {
        name: "facilities_by_city";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          city: string;
          /** @sqlType BIGINT */
          facilities: number;
        }>;
      };
    facilities_by_specialty: {
        name: "facilities_by_specialty";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          specialty: string;
          /** @sqlType BIGINT */
          facilities: number;
        }>;
      };
    facilities_directory: {
        name: "facilities_directory";
        parameters: {
          /** STRING - use sql.string() */
          search: SQLStringMarker;
          /** INT - use sql.int() */
          min_beds: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          unique_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType INT */
          doctors: number;
          /** @sqlType INT */
          beds: number;
          /** @sqlType STRING */
          phone: string;
          /** @sqlType STRING */
          email: string;
          /** @sqlType STRING */
          website: string;
        }>;
      };
    facility_kpis: {
        name: "facility_kpis";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          total_facilities: number;
          /** @sqlType BIGINT */
          cities: number;
          /** @sqlType DOUBLE */
          avg_doctors: number;
          /** @sqlType BIGINT */
          total_beds: number;
          /** @sqlType DECIMAL(25,0) */
          pct_online: number;
        }>;
      };
    facility_locations: {
        name: "facility_locations";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          unique_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          country: string;
          /** @sqlType DOUBLE */
          latitude: number;
          /** @sqlType DOUBLE */
          longitude: number;
          /** @sqlType INT */
          beds: number;
          /** @sqlType INT */
          doctors: number;
          /** @sqlType STRING */
          website: string;
          /** @sqlType STRING */
          phone: string;
        }>;
      };
  }
}
